// Generated by gencpp from file car_msgs/vehicle_state.msg
// DO NOT EDIT!


#ifndef CAR_MSGS_MESSAGE_VEHICLE_STATE_H
#define CAR_MSGS_MESSAGE_VEHICLE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace car_msgs
{
template <class ContainerAllocator>
struct vehicle_state_
{
  typedef vehicle_state_<ContainerAllocator> Type;

  vehicle_state_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , timestamp(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , heading(0.0)
    , kappa(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , linear_acceleration(0.0)  {
    }
  vehicle_state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , timestamp(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , heading(0.0)
    , kappa(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , linear_acceleration(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _kappa_type;
  _kappa_type kappa;

   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef double _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;





  typedef boost::shared_ptr< ::car_msgs::vehicle_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_msgs::vehicle_state_<ContainerAllocator> const> ConstPtr;

}; // struct vehicle_state_

typedef ::car_msgs::vehicle_state_<std::allocator<void> > vehicle_state;

typedef boost::shared_ptr< ::car_msgs::vehicle_state > vehicle_statePtr;
typedef boost::shared_ptr< ::car_msgs::vehicle_state const> vehicle_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_msgs::vehicle_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_msgs::vehicle_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace car_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'car_msgs': ['/home/wf/my-code/auto-car/ros/src/car_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::vehicle_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::vehicle_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_msgs::vehicle_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_msgs::vehicle_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::vehicle_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::vehicle_state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_msgs::vehicle_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd35b73d23a93129fd1102fc7d8bf74f";
  }

  static const char* value(const ::car_msgs::vehicle_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd35b73d23a93129ULL;
  static const uint64_t static_value2 = 0xfd1102fc7d8bf74fULL;
};

template<class ContainerAllocator>
struct DataType< ::car_msgs::vehicle_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_msgs/vehicle_state";
  }

  static const char* value(const ::car_msgs::vehicle_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_msgs::vehicle_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 timestamp\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
float64 heading\n\
float64 kappa\n\
float64 linear_velocity\n\
float64 angular_velocity\n\
float64 linear_acceleration\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::car_msgs::vehicle_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_msgs::vehicle_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.timestamp);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.heading);
      stream.next(m.kappa);
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
      stream.next(m.linear_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehicle_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_msgs::vehicle_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_msgs::vehicle_state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "kappa: ";
    Printer<double>::stream(s, indent + "  ", v.kappa);
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "linear_acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.linear_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MSGS_MESSAGE_VEHICLE_STATE_H
