// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_conf.proto

#include "control_conf.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_lon_5fcontroller_5fconf_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_LonControllerConf_lon_5fcontroller_5fconf_2eproto;
namespace autocar {
namespace control {
class ControlConfDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ControlConf> _instance;
} _ControlConf_default_instance_;
}  // namespace control
}  // namespace autocar
static void InitDefaultsControlConf_control_5fconf_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::autocar::control::_ControlConf_default_instance_;
    new (ptr) ::autocar::control::ControlConf();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::autocar::control::ControlConf::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ControlConf_control_5fconf_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsControlConf_control_5fconf_2eproto}, {
      &scc_info_LonControllerConf_lon_5fcontroller_5fconf_2eproto.base,}};

void InitDefaults_control_5fconf_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ControlConf_control_5fconf_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_control_5fconf_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_control_5fconf_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_control_5fconf_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_control_5fconf_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::autocar::control::ControlConf, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::autocar::control::ControlConf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::autocar::control::ControlConf, lon_controller_conf_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::autocar::control::ControlConf)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::autocar::control::_ControlConf_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_control_5fconf_2eproto = {
  {}, AddDescriptors_control_5fconf_2eproto, "control_conf.proto", schemas,
  file_default_instances, TableStruct_control_5fconf_2eproto::offsets,
  file_level_metadata_control_5fconf_2eproto, 1, file_level_enum_descriptors_control_5fconf_2eproto, file_level_service_descriptors_control_5fconf_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_control_5fconf_2eproto = {
  false, InitDefaults_control_5fconf_2eproto, 
  "\n\022control_conf.proto\022\017autocar.control\032\031l"
  "on_controller_conf.proto\"N\n\013ControlConf\022"
  "\?\n\023lon_controller_conf\030\001 \001(\0132\".autocar.c"
  "ontrol.LonControllerConf"
,
  "control_conf.proto", &assign_descriptors_table_control_5fconf_2eproto, 144,
};

void AddDescriptors_control_5fconf_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_lon_5fcontroller_5fconf_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_control_5fconf_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_control_5fconf_2eproto = []() { AddDescriptors_control_5fconf_2eproto(); return true; }();
namespace autocar {
namespace control {

// ===================================================================

void ControlConf::InitAsDefaultInstance() {
  ::autocar::control::_ControlConf_default_instance_._instance.get_mutable()->lon_controller_conf_ = const_cast< ::autocar::control::LonControllerConf*>(
      ::autocar::control::LonControllerConf::internal_default_instance());
}
class ControlConf::HasBitSetters {
 public:
  static const ::autocar::control::LonControllerConf& lon_controller_conf(const ControlConf* msg);
  static void set_has_lon_controller_conf(ControlConf* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

const ::autocar::control::LonControllerConf&
ControlConf::HasBitSetters::lon_controller_conf(const ControlConf* msg) {
  return *msg->lon_controller_conf_;
}
void ControlConf::clear_lon_controller_conf() {
  if (lon_controller_conf_ != NULL) lon_controller_conf_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ControlConf::kLonControllerConfFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ControlConf::ControlConf()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:autocar.control.ControlConf)
}
ControlConf::ControlConf(const ControlConf& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_lon_controller_conf()) {
    lon_controller_conf_ = new ::autocar::control::LonControllerConf(*from.lon_controller_conf_);
  } else {
    lon_controller_conf_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:autocar.control.ControlConf)
}

void ControlConf::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ControlConf_control_5fconf_2eproto.base);
  lon_controller_conf_ = NULL;
}

ControlConf::~ControlConf() {
  // @@protoc_insertion_point(destructor:autocar.control.ControlConf)
  SharedDtor();
}

void ControlConf::SharedDtor() {
  if (this != internal_default_instance()) delete lon_controller_conf_;
}

void ControlConf::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ControlConf& ControlConf::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ControlConf_control_5fconf_2eproto.base);
  return *internal_default_instance();
}


void ControlConf::Clear() {
// @@protoc_insertion_point(message_clear_start:autocar.control.ControlConf)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(lon_controller_conf_ != NULL);
    lon_controller_conf_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ControlConf::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ControlConf*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ::google::protobuf::uint32 tag;
    ptr = Varint::Parse32Inline(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional .autocar.control.LonControllerConf lon_controller_conf = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = Varint::Parse32Inline(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::autocar::control::LonControllerConf::_InternalParse;
        object = msg->mutable_lon_controller_conf();
        if (size > end - ptr) goto len_delim_till_end;
        auto newend = ptr + size;
        bool ok = ctx->ParseExactRange({parser_till_end, object},
                                       ptr, newend);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ok);
        ptr = newend;
        break;
      }
      default: {
      handle_unusual: (void)&&handle_unusual;
        if ((tag & 7) == 4 || tag == 0) {
          bool ok = ctx->ValidEndGroup(tag);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ok);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end: (void)&&len_delim_till_end;
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                                 {parser_till_end, object}, size);
group_continues: (void)&&group_continues;
  GOOGLE_DCHECK(ptr >= end);
  ctx->StoreGroup({_InternalParse, msg}, {parser_till_end, object}, depth);
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ControlConf::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:autocar.control.ControlConf)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .autocar.control.LonControllerConf lon_controller_conf = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_lon_controller_conf()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:autocar.control.ControlConf)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:autocar.control.ControlConf)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ControlConf::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:autocar.control.ControlConf)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .autocar.control.LonControllerConf lon_controller_conf = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::lon_controller_conf(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:autocar.control.ControlConf)
}

::google::protobuf::uint8* ControlConf::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:autocar.control.ControlConf)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .autocar.control.LonControllerConf lon_controller_conf = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::lon_controller_conf(this), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:autocar.control.ControlConf)
  return target;
}

size_t ControlConf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:autocar.control.ControlConf)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .autocar.control.LonControllerConf lon_controller_conf = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *lon_controller_conf_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ControlConf::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:autocar.control.ControlConf)
  GOOGLE_DCHECK_NE(&from, this);
  const ControlConf* source =
      ::google::protobuf::DynamicCastToGenerated<ControlConf>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:autocar.control.ControlConf)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:autocar.control.ControlConf)
    MergeFrom(*source);
  }
}

void ControlConf::MergeFrom(const ControlConf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:autocar.control.ControlConf)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_lon_controller_conf()) {
    mutable_lon_controller_conf()->::autocar::control::LonControllerConf::MergeFrom(from.lon_controller_conf());
  }
}

void ControlConf::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:autocar.control.ControlConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlConf::CopyFrom(const ControlConf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:autocar.control.ControlConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlConf::IsInitialized() const {
  return true;
}

void ControlConf::Swap(ControlConf* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ControlConf::InternalSwap(ControlConf* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(lon_controller_conf_, other->lon_controller_conf_);
}

::google::protobuf::Metadata ControlConf::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_control_5fconf_2eproto);
  return ::file_level_metadata_control_5fconf_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace control
}  // namespace autocar
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::autocar::control::ControlConf* Arena::CreateMaybeMessage< ::autocar::control::ControlConf >(Arena* arena) {
  return Arena::CreateInternal< ::autocar::control::ControlConf >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
