#include "control/pid_controller.h"
#include "msgs/chassisCommand.h"
#include "msgs/chassis.h"
#include "msgs/localization.h"
#include "msgs/trajectory.h"

class LonControllerConf{
    public:
        LonControllerConf(){};
        virtual ~LonControllerConf(){};

        double ts;
        PidConf station_pid_conf;
        PidConf speed_pid_conf;
};

class LonController {
 public:
  /**
   * @brief initialize Longitudinal Controller
   * @param control_conf control configurations
   * @return Status initialization status
   */
  bool Init(const LonControllerConf *control_conf);

  /**
   * @brief compute brake / throttle values based on current vehicle status
   *        and target trajectory
   * @param localization vehicle location
   * @param chassis vehicle status e.g., speed, acceleration
   * @param trajectory trajectory generated by planning
   * @param cmd control command
   * @return Status computation status
   */
  double ComputeControlCommand(
      const msgs::localization *localization,
      const msgs::chassis *chassis, const msgs::trajectory *trajectory,
      msgs::chassisCommand *cmd);

  /**
   * @brief reset longitudinal controller
   * @return Status reset status
   */
  bool Reset();

  /**
   * @brief stop longitudinal controller
   */
  void Stop();

 protected:

  double ts_;
  PIDController station_pid_controller_;
  PIDController speed_pid_controller_;
};

